# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170410_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='object'),
        ),
    ]
