# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170410_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
